### ISSUE TITLE
Unable to provide a Linkedin url containing an accent

### ISSUE THREAD

**Issue by reda-alaoui** [borisghidaglia/meet-hn#7]
My Linkedin profile is https://fr.linkedin.com/in/r%C3%A9da-housni-alaoui-19970116 because of an accent on my first name.

My HN profile is https://news.ycombinator.com/user?id=reda-alaoui .

The about section is:
```

meet.hn/city/fr-Paris

Socials:
- github.com/reda-alaoui
- linkedin.com/in/r%C3%A9da-housni-alaoui-19970116

Interests:
Programming, Open Source, Networking

---
```

On meet.hn, the linkedin url is trimmed to https://linkedin.com/in/r .

**Comment by borisghidaglia** [comment]
Hey @reda-alaoui, thanks for reporting!

I'm actually in the process of gathering all the feedbacks hackers made since launch day, and this was already on the list! 
Sorry for this, it's pretty painful. 
I'll comment here when it's fixed.

**Comment by borisghidaglia** [comment]
Should be fixed now! Tell me if it works on your side as well @reda-alaoui

**Comment by reda-alaoui** [comment]
@borisghidaglia it works, thanks !
